[tasks.all]
dependencies = ["format", "build", "clippy", "test", "doc"]

[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.build]
command = "cargo"
args = ["build"]
dependencies = ["clean"]

[tasks.clippy]
command = "cargo"
args = ["clippy"]
dependencies = ["clean"]

[tasks.test]
command = "cargo"
args = ["test"]
dependencies = ["clean"]

[tasks.doc]
command = "cargo"
args = ["doc"]
dependencies = ["clean"]